---
title: "Education"
---


# PENN STATE UNIVERSITY

## 2020 - 2024

I began my higher education journey at Penn State University (PSU) - University Park, where I earned a Bachelor of Science degree in Biology in May 2024. During my time at PSU, I participated in various events and had the opportunity to connect with a diverse group of individuals. In addition, I was surrounded by inspiring faculty, and enaging mentors throughout college. The opportunities I had at Penn State led me to exploring different types of research. My time at PSU inspired me to pursue a doctoral degree and further advance my research career.


# CASE WESTERN RESERVE UNIVERSITY

## 2024-2025

Currently, I am working as a Case PREP Scholar at Case Western Reserve University (CWRU). This is an incredible opportunity that has allowed me to learn and expand my knowledge of biomedical science research. I am focused on researching cancer and obesity. Outside of the lab, I frequently attend seminars, symposiums, and study around various spots on campus. Being here has allowed me to develop my professional skills, and has prepared me for graduate school. 


# UNIVERSITY OF MICHIGAN

## 2025 - 2030 

I’m excited to announce that I’ll be continuing my journey at the University of Michigan! I was accepted into their Programs in Biomedical Science (PIBS) PhD Umbrella program. I am interested in umbrella programs because I will get the opportunity to rotate in multiple labs that pique my interest. This section will be updated once I begin my rotations and finish my first week of classes. I am so grateful for this opportunity! 


And of course, Go Blue!
